export * from './createStudent.service'
export * from './dashStudent.service'
export * from './listStudent.service'
export * from './resumeStudent.service'
export * from './retrieveStudent.service'
export * from './updateStudent.service'
