export * from './createSchool.service'
export * from './dashSchool.service'
export * from './deleteSchool.service'
export * from './listSchool.service'
export * from './retrieveSchool.service'
export * from './updateSchool.service'
export * from './verifySchool.service'
